### ISSUE TITLE
Regarding PEMS08 dataset

### ISSUE THREAD

**Issue by sugar-hub** [jeongwhanchoi/STG-NRDE#2]
Hi, thanks for your contribution! When I choose PEMS08 dataset and run the model, I get the wrong report as follows:

Traceback (most recent call last):
  File "Run.py", line 225, in <module>
    trainer.train()
  File "/root/autodl-tmp/STG-NRDE-main/model/BasicTrainer_cde.py", line 130, in train
    train_epoch_loss = self.train_epoch(epoch)
  File "/root/autodl-tmp/STG-NRDE-main/model/BasicTrainer_cde.py", line 91, in train_epoch
    output = self.model(self.times, train_coeffs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/STG-NRDE-main/model/GRDE.py", line 96, in forward
    z_T = torchcde.cdeint_custom(X=X,
  File "/root/autodl-tmp/STG-NRDE-main/torchcde/solver.py", line 389, in cdeint_custom
    out = odeint(func=vector_field, y0=z0, t=t, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/adjoint.py", line 206, in odeint_adjoint
    ans = OdeintAdjointMethod.apply(shapes, func, y0, t, rtol, atol, method, options, event_fn, adjoint_rtol, adjoint_atol,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/adjoint.py", line 24, in forward
    ans = odeint(func, y0, t, rtol=rtol, atol=atol, method=method, options=options, event_fn=event_fn)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/odeint.py", line 80, in odeint
    solution = solver.integrate(t)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/solvers.py", line 114, in integrate
    dy, f0 = self._step_func(self.func, t0, dt, t1, y0)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/fixed_grid.py", line 28, in _step_func
    f0 = func(t0, y0, perturb=Perturb.NEXT if self.perturb else Perturb.NONE)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/misc.py", line 197, in forward
    return self.base_func(t, y)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/misc.py", line 197, in forward
    return self.base_func(t, y)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torchdiffeq/_impl/misc.py", line 144, in forward
    f = self.base_func(t, _flat_to_shape(y, (), self.shapes))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/STG-NRDE-main/torchcde/solver.py", line 279, in forward
    vector_field_g = self.func_g(t, z)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/STG-NRDE-main/model/vector_fields.py", line 408, in forward
    z = self.agc(z)
  File "/root/autodl-tmp/STG-NRDE-main/model/vector_fields.py", line 444, in agc
    x_g = torch.einsum("knm,bmc->bknc", supports, z)      #B, cheb_k, N, dim_in
  File "/root/miniconda3/lib/python3.8/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): subscript m has size 170 for operand 1 which does not broadcast with previously seen size 307

it seems that 307 is the num_node of PEMS04 and 170 is the num_node of PEMS08. How to fix this problem?

**Comment by sugar-hub** [comment]
I found it! In Run.py, line27. You should change the dataset name manually.
